---
#########################################################
## Set action                                          ##
#########################################################

- name: Set action to install
  ansible.builtin.set_fact:
    action: "install"